#version: '3.8'  # Recomendado agregarlo

services:
  frontend:
    build: ./FRONTEND
    ports:
      - "5173:80"
    env_file:
      - ./FRONTEND/.env
    depends_on:
      - backend

  backend:
    build: ./BACKEND
    ports:
      - "4001:4001"
      - "5555:5555" # Necesario para Prisma Studio
    env_file:
      - ./BACKEND/.env.docker
    environment:
      - DATABASE_URL=postgresql://postgres:12345@postgres:5432/nodepg # 👈 TU USUARIO, CONTRASEÑA Y DB CAMBIADOS A LOS REALES
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=nodepg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
