name: Fullstack CI

on:
  push:
    branches: ["main", "develop", "feature/*"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      ## FRONTEND
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./FRONTEND

      - name: Run Frontend Tests
        run: npm run test -- --watchAll=false
        working-directory: ./FRONTEND

      - name: Build Frontend Project
        run: npm run build
        working-directory: ./FRONTEND

      ## BACKEND
      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./BACKEND

      - name: Run Backend Tests
        run: npm test
        working-directory: ./BACKEND
